---

- name: "[ENTERPRISE-DEMO][AWS][DEPLOY-INSTANCE] Add IP into Custom CMDB"
  hosts: all
  #vars:
  #  new_vm_ip: 10.32.170.150

  tasks:
    - name: "Add {{ new_vm_ip }} to Dynamic inventory"
      uri:
        url: "http://10.32.170.153/add_ip.php?ip={{ new_vm_ip }}"
        method: GET
        return_content: no
