---

- name: "Clean nagios alarms for cloud environments"
  hosts: all
  connection: local
  tasks:

   - name: "Delete configuration file (server_id.cfg) for the server"
     delegate_to: 10.32.170.152
     shell: rm -f /etc/nagios/servers/{{ new_vm_ip }}.cfg

   - name: "Restart nagios service"
     delegate_to: 10.32.170.152
     service:
       name: nagios
       state: restarted
