---
# This playbook deploys two simple applications to JBoss server.

- name: "[ENTERPRISE-DEMO][AWS][DEPLOY-AWS] Add ec2-instance to the inv"
  hosts: localhost
  connection: local
  remote_user: "{{ ec2_remote_user }}"
  vars_files:
    - "vault/aws_vault.yml"
  roles:
    - { role: provision-vm }

- name: "[ENTERPRISE-DEMO][AWS][CONFIG-JBOSS] Configure APP in JBOSS standalone in the ec2 server"
  hosts: aws_inv
  remote_user: "{{ ec2_remote_user }}"
  become: yes
  vars_files:
    - "vault/aws_vault.yml"
  roles:
    - { role: tomcat-selinux }
    - { role: tomcat-standalone }
