---

- name: "Clean cloud environments"
  hosts: all
  connection: local
  vars_files:
    - "vault/aws_vault.yml"
  tasks:
   - name: "Get facts about instance in ec2"
     ec2_instance_facts:
       filters:
         "tag:Name": "{{ ec2_instance_name }}"
       region: "{{ ec2_region }}"
     register: instances

   - name: "Register the variables"
     set_stats:
       data:
         new_vm_ip: "{{ item.public_dns_name }}"
       per_host: no
       aggregate: no
     with_items: "{{ instances }}"
