---

- name: "Clean cloud environments"
  hosts: all
  connection: local
  vars_files:
    - "vault/aws_vault.yml"
  tasks:
   - name: "Get facts about instance in ec2"
     ec2_instance_facts:
       access_key: "{{ ec2_access_key }}"
       secret_key: "{{ ec2_secret_key }}"
       filters:
         "tag:Name": "{{ ec2_instance_name }}"
       region: "{{ ec2_region }}"
     register: instances

   - debug:
       msg: "{{ instances }}"

   - name: "Register the variables"
     set_stats:
       data:
         new_vm_ip: "{{ instances.public_dns_name }}"
       per_host: no
       aggregate: no
