---

- name: Delete an instance and its resources
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    project: my-project
    gcp_cred_kind: serviceaccount
    gcp_cred_file: 
    image: 'projects/rhel-cloud/global/images/rhel-7-v20190116'
    zone: "europe-west1-b"
    region: "europe-west1"
    disk_name: 'disk-instance'
    disk_size_gb: 10
    network_name: 'network-instance'
    address_name: 'address-instance'
    vm_name: 'test-vm'
    instance_state: "absent"

  tasks:
    - name: delete instance and disk (if configured to be deleted with the instance)
      gcp_compute_instance:
        state: "{{ instance_state }}"
        name: "{{ vm_name}}"
        #machine_type: n1-standard-1
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        metadata:
          istest: true
        scopes:
          - https://www.googleapis.com/auth/compute

    - name: delete network
      gcp_compute_network:
        name: "{{ network_name}}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: "{{ instance_state }}"
     # register: network

    - name: delete address
      gcp_compute_address:
        name: "{{ address_name}}"
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: "{{ instance_state }}"

